/*
Component implemented by Anastasiia Seemnova (stacy22@bu.edu)
It is a slideshow component for cycling through slides of text like a carousel.
Each slide is a job searching tip. Tips were generated by ChatGPT, but code is my own.

The idea is borrowed from this website
https://react-bootstrap.netlify.app/docs/components/carousel/
("controlled" example)
 */

import { useState } from 'react';

// prebuilt Bootstrap-styled carousel
import Carousel from 'react-bootstrap/Carousel';

import styled from 'styled-components';

// matches the Header styling
const FooterDiv = styled.footer`
  width: 100%;
  padding: 5%;
  background-color: black;
  color: white;
  text-align: center;
  box-sizing: border-box;
`;

// makes sure slides have enough space
const SlideContent = styled.div`
  height: 200px;
`;

// used ChatGPT to generate some tips (not the code itself)
// 10 tips in total, each tip has a title and a description.
// array will be used to dynamically generate each carousel slide using .map()
const tips = [
    {
        title: "Refine your LinkedIn headline",
        description: "Use your headline to summarize what you do and the value you offer, not just your job title."
    },
    {
        title: "Apply early in the posting window",
        description: "Remote roles often fill quickly. Applying within the first few days increases your chances of being seen."
    },
    {
        title: "Keep your resume metrics-driven",
        description: "Whenever possible, show outcomes with numbers, not just responsibilities."
    },
    {
        title: "Research each company thoroughly",
        description: "Tailor your application to reflect the company’s mission, culture, and recent work."
    },
    {
        title: "Stay consistent across platforms",
        description: "Your resume, LinkedIn, and portfolio should align in tone, experience, and branding."
    },
    {
        title: "Prepare structured interview answers",
        description: "Use frameworks like STAR (Situation, Task, Action, Result) to organize your responses clearly."
    },
    {
        title: "Demonstrate remote work experience",
        description: "Highlight any projects, freelancing, or prior remote roles that show you can work independently."
    },
    {
        title: "Prioritize asynchronous communication skills",
        description: "Remote teams rely heavily on clear written updates. Show you can communicate effectively without needing live meetings."
    },
    {
        title: "Understand international employment logistics",
        description: "If applying globally, be aware of time zone overlaps, tax laws, and contract work norms."
    },
    {
        title: "Stay professional in all communications",
        description: "Every email, message, and interaction is evaluated. Communicate promptly, clearly, and respectfully."
    }

];

// my component
export default function Footer() {
    // set at 0 so that first slide is shown initially
    const [index, setIndex] = useState(0);

    // updates the index state when arrows are clicked
    const handleSelect = (selectedIndex: number) => {
        setIndex(selectedIndex);
    };

    /*
    Part of the following code is from the website mentioned above.
    I added the "mapping" over the tips array.
     */
    return (
        <FooterDiv>
            <Carousel activeIndex={index} onSelect={handleSelect}>
                {tips.map((tip, item) => (
                    <Carousel.Item key={item}>
                        <SlideContent />
                        <Carousel.Caption>
                            <h3>{tip.title}</h3>
                            <p>{tip.description}</p>
                        </Carousel.Caption>
                    </Carousel.Item>
                ))}
            </Carousel>
        </FooterDiv>
    );
}
